[  ](bg:#bfcfff fg:#474e66)\
[$username]()\
[]()\
[]()\
[$directory]()\
[ ]()
"""

add_newline = false

[username]
show_always = true
style_user = "bg:#bfcfff fg:#474e66"
format = "[$user ]($style)"

[directory]
style = "bg:#bfcfff fg:#474e66"
truncation_length = 1
truncation_symbol = ""
format = "[ $path ]($style)" 
