format = """$username $directory$cmd_duration $character"""

# Padding between prompts
add_newline = false

# Set the standard characters to use in the prompt
[character]
success_symbol = "[->](bold purple)"
error_symbol = "[<-](bold red)"

# Prints how long you used a command for e.g opening vim for 2 seconds
[cmd_duration]
min_time = 1
format = "🚀 [$duration](bold yellow)"
disabled = false
show_notifications = false

[directory]
truncation_length = 7
truncation_symbol = "…/"

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[💻]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '@[$hostname](bold red) '
trim_at = "."
disabled = false

[localip]
ssh_only = false
format = "@[$localipv4](bold red) "
disabled = false
